name: "Roger That! Action"
description: "Roger That! Action to test actions..."
inputs:
  name:
    description: "Name to say Hello"
runs:
  using: "composite"
  steps:
    - name: Test exit codes
      shell: bash
      run: |
        exit 1 > /dev/null 2>&1
