name: "Roger That! Action"
description: "Roger That! Action to test actions..."
inputs:
  name:
    description: "Name to say Hello"
runs:
  using: "composite"
    - name: Say Hello!
      shell: bash
      run: |
        NAME=${{inputs.name}}
        ./entrypoint.sh