name: "Roger That! Action"
description: "Roger That! Action to test actions..."
inputs:
  name:
    description: "Name to say Hello"
runs:
  using: "composite"
  steps:
    - name: Test exit codes
      shell: bash
      run: |
        echo "::warning::Quality gate locks manually disabled by registering the \`SKIP_QUALITY_GATE_LOCK\` variable!"
