name: "Roger That! Action"
description: "Roger That! Action to test actions..."
inputs:
  name:
    description: "Name to say Hello"
runs:
  using: "composite"
  steps:
    - name: Say Hello!
      shell: bash
      run: |
        NAME=${{inputs.name}}
        ./entrypoint.sh
  using: "composite"
  steps:
    - name: Test
      shell: bash
      run: | 
        echo "It works!"
