name: Test Trigger
on:
  workflow_run:
    branches: main
    workflows: ["Hello"]
    types: completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
