name: Test Quality Gate

on:
  pull_request:

jobs:
  quality-gate:
    if: github.base_ref == github.event.repository.default_branch
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quality Gate Action
        uses: olxbr/quality-gate-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_check_timeout: ${{ vars.SONAR_CHECK_TIMEOUT }}
          unit_test_check_timeout: ${{ vars.UNIT_TEST_CHECK_TIMEOUT }}
          gates_to_skip: ${{ vars.GATES_TO_SKIP }}
          docs_url: "https://olxbr.atlassian.net/l/cp/N6utuY5U"
