name: Quality Gate

on:
  pull_request:

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  quality-gate:
    if: github.base_ref == github.event.repository.default_branch
    name: Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Quality Gate Action
        uses: olxbr/quality-gate-action@feat/vulnerability-gate-2
        with:
          github_token: ${{ secrets.OLXBR_BOT_PAT_GH_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_check_timeout: ${{ vars.SONAR_CHECK_TIMEOUT }}
          unit_test_check_timeout: ${{ vars.UNIT_TEST_CHECK_TIMEOUT }}
          gates_to_skip: ${{ vars.GATES_TO_SKIP }}
          docs_url: "https://olxbr.atlassian.net/l/cp/N4UW24eb"
          gh_metrics_server_endpoint: "https://6595928a04335332df82f869.mockapi.io"
  
  skip-quality-gate-for-non-default-branch:
    if: github.base_ref != github.event.repository.default_branch
    name: Skip Quality Gate (Non default branch)
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          ## PR DIFFERENT OF DEFAULT BRANCH
          echo "Skipped"
