name: Test Workflow Call

on:
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: ${{ github.repository }}

jobs:
  test-wf-call:
    uses: olxbr/$REPO_NAME/.github/workflows/unit-tests.yml@main
