name: Test Workflow Call

on:
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UNIT_TEST_WORKFLOW: "unit-tests.yml"

jobs:
  # TEST Failed!
  # test-wf-call:
  #   uses: ./.github/workflows/unit-tests.yml
  test-repo-dispatch:
    name: Testing Repo Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Trigger unit test wf
        run: |
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows/${{ env.UNIT_TEST_WORKFLOW }}/dispatches \
              -d '{"ref":"main"}'
