name: Test Quality Gate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Quality Gate Action
        uses: olxbr/quality-gate-action@feat/results-presentation
        with:
          github_token: ${{ secrets.OLXBR_BOT_PAT_GH_TOKEN }}
